#!/usr/bin/env python3

import rospy
from std_msgs.msg import Int32
from otomo_msgs.msg import Joystick

msg_recvd = False
stop_pub = rospy.Publisher('/manual/joystick', Joystick, queue_size=1)

def client_cb(_):
    global msg_recvd
    msg_recvd = True

def timeout(_):
    global msg_recvd
    if msg_recvd == False:
        msg = Joystick()
        msg.heading = 0
        msg.speed = 0
        stop_pub.publish(msg)
    else:
        msg_recvd = False

if __name__ == '__main__':
    rospy.init_node('otomo_webserver_heartbeat')
    heartbeat_sub = rospy.Subscriber('/webclient/heartbeat', Int32, client_cb)
    heartbeat_timer = rospy.Timer(rospy.Duration(1), timeout)
    rospy.spin()
